#!/usr/bin/env python
"""END-TO-END FUSION DISTILLATION — LoRA-fine-tune the LM (14B) so the FUSED SLM+LM output reproduces the
full-context LM-teacher (see LORA_FUSION_FT_PLAN.md).

In 'ours', the LM sees query+reasoning but NEVER the context, so it is off-distribution. We teacher-force the
teacher's [reasoning + Final Answer] token sequence through the ACTUAL fusion and train ONLY the LM-LoRA:

  slm_logits = SLM( [SLM_prefix(full context) ++ y] )   # frozen, no_grad
  lm_logits  = LM(  [LM_prefix(query only)   ++ y] )     # LoRA, grad
  fused      = lam * slm_logits + (1-lam) * lm_logits    # identical weighted-sum + lam as inference
  loss       = CE(fused, y)  over completion tokens only  # backprop -> LoRA only

The two prefixes are built with the EVAL harness's OWN prompt functions, so train == inference prompt.
Only the LoRA updates -> it learns to COMPLEMENT the frozen SLM so their fusion equals the teacher.

Target y = the teacher log's `teacher.text` (generated by the SAME teacher that is the eval ceiling), rendered
the way the eval pipeline renders it and otherwise UNEDITED — the goal is only that SLM+LM output matches the
teacher's output on any input under any prompt, so the teacher's behaviour is cloned, never curated (no gold
filter, no 'must have reasoned' filter; both exist only as explicitly labelled ablations).

Efficiency: SLM forward is no_grad (no activation memory); the LM grad-forward is over [query ++ ~200-tok
completion] ~= 250 tokens, so 14B-base bf16 (28GB) + 3B (6GB) + tiny LoRA/AdamW fits ONE 96GB GH200.
"""
import os, sys, json, argparse, math, random
os.environ.setdefault("ANSWER_PROMPT_VARIANT", "reason_v3")  # MUST match target-gen AND eval; set before prompt calls
sys.path.insert(0, os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
import torch
import torch.nn.functional as F
from peft import LoraConfig, get_peft_model
from src.models import load_causal_lm, prepare_inputs
from src.data import load_musique_split
from src.gate_kl import TokenAgnosticGateMLP, build_gate_features   # learned per-token fusion gate
import scripts.run_evidence_sketch_experiments as H  # for the EXACT prompt builders


def clean_completion(text, require_reasoning=False):
    """Render the teacher's generation the way the EVAL PIPELINE renders it, and clone THAT. Nothing else.

    ★ THE PRINCIPLE (user, 2026-07-29): the FT's only goal is that SLM+LM produce what the teacher produces,
    for any input and any prompt. So the teacher's OWN behaviour is never edited. If the teacher ignores the
    'reason first' instruction and answers immediately, that is the teacher's behaviour and the student copying
    it is CORRECT — it is not a defect to filter out. The only legitimate transformation is the one the eval
    decoder/extractor already applies to any generation (truncate at a chat-role leak, keep the answer line),
    because text the decoder can never emit is a state the student can never be scored in.

    `require_reasoning` therefore defaults to False and exists ONLY for an explicitly labelled ablation.
    (What DID go wrong is different: the student AMPLIFIED answer-first from the teacher's 26-41% to 71-97%.
    See --loss-norm and --target-terminator for the two mechanisms behind that.)"""
    if not text or not text.strip():
        return None
    for leak in ("Human:", "Assistant:", "<|im_start|>", "<|im_end|>"):
        if leak in text:
            text = text[: text.find(leak)]
    i = text.find("Final Answer:")
    if i < 0:
        return text.rstrip() or None          # no marker = the teacher's actual behaviour; clone it as-is
    if require_reasoning and not text[:i].strip():
        return None
    nl = text.find("\n", i)
    return text[: nl if nl != -1 else len(text)].rstrip()


def load_teacher_targets(path, f1_threshold, require_reasoning=False):
    """teacher log (run_evidence_sketch teacher mode) -> {example_id: completion_text}.
    f1_threshold > 0 filters against the GOLD answer — see the --f1-threshold help; 0 = pure behaviour cloning."""
    out = {}
    for line in open(path):
        line = line.strip()
        if not line:
            continue
        d = json.loads(line)
        t = d.get("teacher") or {}
        if not isinstance(t, dict):
            continue
        if f1_threshold > 0 and float(t.get("f1", 0.0)) < f1_threshold:
            continue
        comp = clean_completion(t.get("text", ""), require_reasoning=require_reasoning)
        if comp:
            out[str(d.get("example_id"))] = comp
    return out


def lr_at(step, n_optim, base_lr, warmup_frac):
    w = max(1, int(warmup_frac * n_optim))
    if step < w:
        return base_lr * (step + 1) / w
    return base_lr  # constant after warmup (matches kvlink_train)


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--teacher-log", default=None, help="run_evidence_sketch teacher-mode log over the TRAIN split")
    ap.add_argument("--lm-model", default="Qwen/Qwen2.5-14B-Instruct")
    ap.add_argument("--slm-model", default="Qwen/Qwen2.5-3B-Instruct")
    ap.add_argument("--sample", type=int, default=4000, help="how many train examples to load (match teacher-gen SAMPLE)")
    ap.add_argument("--doc-number", type=int, default=40)
    ap.add_argument("--max-length", type=int, default=30000)
    ap.add_argument("--lam", type=float, default=0.7, help="fusion weight on SLM (must match eval lambda)")
    ap.add_argument("--f1-threshold", type=float, default=0.0,
                    help="★ GOLD GATE. >0 keeps only targets whose teacher answer scores f1>=T against the GOLD "
                         "answer. The FT objective is BEHAVIOUR CLONING of the teacher (gold appears nowhere in the "
                         "loss), so the default is 0 = no gold anywhere in the pipeline. Set >0 only for a clearly "
                         "labelled 'oracle-filtered teacher' ablation — and then apply it to EVERY source, or the "
                         "mix silently reweights (2026-07-29: QA sources were gated at 0.5 while summarization was "
                         "not, so the surviving mix was not the mix that was designed).")
    ap.add_argument("--require-reasoning", type=int, default=0,
                    help="ABLATION ONLY (default 0 = off). 1 drops teacher targets that jump straight to "
                         "'Final Answer:'. Off by default because the teacher ignoring its own reasoning "
                         "instruction IS the teacher's behaviour, and this FT clones behaviour — it does not "
                         "curate it. See clean_completion().")
    ap.add_argument("--loss-norm", choices=["token", "example"], default="token",
                    help="★ How a target's tokens are weighted. 'example' (the pre-2026-07-29 behaviour) takes the "
                         "MEAN over each target's tokens, so a 4-token 'Final Answer: rock' target puts ~1/4 of its "
                         "gradient on emitting 'Final' as the FIRST token while a 30-token reason+answer target puts "
                         "~1/30 there — short answer-first targets are massively up-weighted, which is how the "
                         "student amplified answer-first from the teacher's 26-41 pct to 71-97 pct. 'token' weights "
                         "every target token equally (mean over tokens across the accumulation window).")
    ap.add_argument("--target-terminator", choices=["both", "newline", "eos", "none"], default="both",
                    help="★ What ENDS the training target. 'none' reproduces the 2026-07 bug: the target was cut "
                         "exactly at the newline after 'Final Answer:', so NO terminator was ever supervised — the "
                         "LoRA could only erode the stop behaviour it never trained, and eval generations ran to the "
                         "max_new cap (0/500 newline-after-answer in every FT'd run vs 94 pct for the teacher). "
                         "'both' (default) supervises the newline AND the EOS token.")
    ap.add_argument("--onpolicy-frac", type=float, default=0.0,
                    help="★ DAgger / on-policy fraction (0 = off, the pure teacher-forcing default). With prob p an "
                         "example is trained on the STUDENT'S OWN prefix instead of the teacher's: the fusion rolls "
                         "out k tokens free-running, then ONE teacher forward (LoRA disabled, full-context prompt) "
                         "labels every position of that prefix with the teacher's argmax, and the fused distribution "
                         "is trained on those labels. Fixes exposure bias — plain teacher forcing only ever shows the "
                         "model states the TEACHER visits, never the ones its own decoding reaches.")
    ap.add_argument("--onpolicy-max-tokens", type=int, default=24,
                    help="cap on the student rollout length k (bounds the extra forwards per example)")
    ap.add_argument("--kl-weight", type=float, default=1.0,
                    help="★ SOFT-TARGET DISTILLATION weight. loss = w*KL(teacher||fused) + (1-w)*CE(hard tokens). "
                         "1.0 = pure KL (default), 0.0 = the pre-2026-08-01 hard-token CE. The teacher's full "
                         "next-token distribution carries the whole vocabulary's worth of signal per position; "
                         "hard CE threw all of it away and kept only the argmax.")
    ap.add_argument("--kl-temperature", type=float, default=1.0,
                    help="Softmax temperature for both sides of the KL (gradients rescaled by tau^2 as usual).")
    ap.add_argument("--max-comp-tokens", type=int, default=256)
    ap.add_argument("--lora-r", type=int, default=16)
    ap.add_argument("--lora-alpha", type=int, default=32)
    ap.add_argument("--lora-dropout", type=float, default=0.05)
    ap.add_argument("--lr", type=float, default=1e-4)
    ap.add_argument("--epochs", type=float, default=2.0)
    ap.add_argument("--grad-accum", type=int, default=8)
    ap.add_argument("--warmup-frac", type=float, default=0.03)
    ap.add_argument("--grad-clip", type=float, default=1.0)
    ap.add_argument("--seed", type=int, default=0)
    ap.add_argument("--device", default="cuda:0")
    ap.add_argument("--cache-dir", default=os.environ.get("HF_HOME", "/work/hdd/myproject/anon/hf"))
    ap.add_argument("--log-every", type=int, default=20)
    ap.add_argument("--out", required=True, help="adapter output dir")
    ap.add_argument("--max-steps", type=int, default=0, help="cap optimizer updates (0 = use --epochs); for canary")
    ap.add_argument("--train-slm", action="store_true", help="ALSO LoRA-train the SLM (joint SLM+LM fusion FT), not just the LM")
    ap.add_argument("--learn-gate", action="store_true",
                    help="v3: learn a per-token fusion gate λ_t = g(SLM_topk, LM_topk) jointly with the LoRA(s), instead of a "
                         "fixed λ. The gate (TokenAgnosticGateMLP) decides per token how much to trust each branch.")
    ap.add_argument("--gate-top-k", type=int, default=10, help="top-k logits per model fed to the gate (input_dim=2k)")
    ap.add_argument("--gate-hidden", type=int, default=64)
    ap.add_argument("--mix-corpus", default=None,
                    help="BENCHMARK-AGNOSTIC mode: a ft_mix_teacher_gen.py corpus (question/documents/golds/"
                         "teacher_text). Replaces --teacher-log + musique loading, so the adapter is trained on a "
                         "mix that EXCLUDES every eval benchmark (no benchmark-specific FT).")
    a = ap.parse_args()

    _apv = os.environ.get("ANSWER_PROMPT_VARIANT")
    print(f"★ ANSWER_PROMPT_VARIANT={_apv} — this MUST equal the variant used for teacher-target generation AND "
          f"for eval (train/eval prompt mismatch invalidates the adapter).", flush=True)
    random.seed(a.seed); torch.manual_seed(a.seed)

    # 1) targets + examples
    if a.mix_corpus:
        # BENCHMARK-AGNOSTIC: one corpus carries both the example and its teacher target.
        from types import SimpleNamespace
        targets, ex_by_id, bysrc = {}, {}, {}
        for line in open(a.mix_corpus):
            if not line.strip():
                continue
            r = json.loads(line)
            if not r.get("keep"):
                continue                      # per-source FORMAT gate applied at teacher-gen time
            if a.f1_threshold > 0 and not r.get("is_summarization") and float(r.get("teacher_f1", 0.0)) < a.f1_threshold:
                continue                      # opt-in gold gate, applied HERE so it is visible in this run's meta
            comp = clean_completion(r.get("teacher_text", ""), require_reasoning=bool(a.require_reasoning))
            if not comp:
                continue
            eid = str(r["example_id"])
            targets[eid] = comp
            ex_by_id[eid] = SimpleNamespace(example_id=eid, question=r["question"],
                                            documents=list(r["documents"]),
                                            answer=(r["golds"] or [""])[0], answers=list(r["golds"]))
            bysrc[r["source"]] = bysrc.get(r["source"], 0) + 1
        ids = list(targets)
        print(f"[Info] MIX corpus {a.mix_corpus}: {len(ids)} usable targets by source={bysrc}", flush=True)
    else:
        targets = load_teacher_targets(a.teacher_log, a.f1_threshold, require_reasoning=bool(a.require_reasoning))
        print(f"[Info] {len(targets)} targets (gold-gate f1>={a.f1_threshold}, require_reasoning="
              f"{bool(a.require_reasoning)}) from {a.teacher_log}", flush=True)
        examples = load_musique_split("train", cache_dir=a.cache_dir, sample=a.sample, doc_number=a.doc_number)
        ex_by_id = {str(e.example_id): e for e in examples}
        ids = [i for i in targets if i in ex_by_id]
        print(f"[Info] {len(ids)} examples matched (train ids ∩ targets)", flush=True)
    if not ids:
        print("❌ no matched examples — check --sample matches the teacher-gen SAMPLE and split.", flush=True); sys.exit(2)

    # 2) models: LM base frozen + LoRA trainable; SLM frozen (no_grad) unless --train-slm (then LoRA it too)
    slm, slm_tok = load_causal_lm(a.slm_model, cache_dir=a.cache_dir, device_map=a.device)
    lm, lm_tok = load_causal_lm(a.lm_model, cache_dir=a.cache_dir, device_map=a.device)
    lcfg = LoraConfig(r=a.lora_r, lora_alpha=a.lora_alpha, lora_dropout=a.lora_dropout, bias="none",
                      task_type="CAUSAL_LM",
                      target_modules=["q_proj", "k_proj", "v_proj", "o_proj", "gate_proj", "up_proj", "down_proj"])
    lm = get_peft_model(lm, lcfg); lm.train()
    print("[LM]  ", end=""); lm.print_trainable_parameters()
    if a.train_slm:
        slm = get_peft_model(slm, lcfg); slm.train()
        slm.gradient_checkpointing_enable(); slm.enable_input_require_grads()  # SLM forward is long-ctx -> checkpoint
        print("[SLM] ", end=""); slm.print_trainable_parameters()
    else:
        slm.eval()
        for p in slm.parameters():
            p.requires_grad_(False)
    dev = next(lm.parameters()).device

    # reference target length for --loss-norm token (computed once over the corpus, so the gradient scale
    # matches the old per-example normalization on average and only the RELATIVE weighting changes)
    _tl = [len(lm_tok(t, add_special_tokens=False)["input_ids"]) for t in targets.values()]
    t_ref = max(1.0, sum(_tl) / max(1, len(_tl)))
    print(f"[Info] loss_norm={a.loss_norm} mean_target_tokens={t_ref:.1f} "
          f"(min={min(_tl) if _tl else 0} max={max(_tl) if _tl else 0})", flush=True)

    n_micro_per_epoch = len(ids)
    total_micro = int(a.epochs * n_micro_per_epoch)
    n_optim = max(1, total_micro // a.grad_accum)
    if a.max_steps > 0:
        n_optim = min(n_optim, a.max_steps)
        total_micro = n_optim * a.grad_accum
    trainable = [p for p in lm.parameters() if p.requires_grad]
    if a.train_slm:
        trainable += [p for p in slm.parameters() if p.requires_grad]
    gate = None
    if a.learn_gate:
        gate = TokenAgnosticGateMLP(input_dim=2 * a.gate_top_k, hidden_dim=a.gate_hidden, mlp_layers=1).to(dev).train()
        trainable += list(gate.parameters())
        ng = sum(p.numel() for p in gate.parameters())
        print(f"[GATE] learned per-token gate: TokenAgnosticGateMLP(in={2*a.gate_top_k}, hid={a.gate_hidden}) — {ng} params", flush=True)
    # ★ PREFLIGHT SAVE (2026-08-03). Job 2830021 ran 2000/2000 steps over 3h46m and then died in
    # save_pretrained with "Disk quota exceeded" — the adapter was lost and every chained eval went
    # DependencyNeverSatisfied. Prove the EXACT save path works, with the EXACT call and the real
    # tensor sizes, BEFORE spending the GPU hours. Costs a few seconds.
    os.makedirs(a.out, exist_ok=True)
    try:
        lm.save_pretrained(a.out)
        if a.train_slm:
            slm.save_pretrained(a.out.rstrip("/") + "_slmada")
        print(f"[Preflight] save path OK -> {a.out}", flush=True)
    except Exception as e:
        print(f"❌ PREFLIGHT SAVE FAILED ({type(e).__name__}: {e})\n"
              f"   Not starting training — free space / fix permissions for {a.out} first.", flush=True)
        sys.exit(3)

    opt = torch.optim.AdamW(trainable, lr=a.lr)
    print(f"[Info] micro={total_micro} optim_updates={n_optim} grad_accum={a.grad_accum} lr={a.lr} lam={a.lam} train_slm={a.train_slm}", flush=True)

    # 3) train loop — random example per microstep (with-replacement across the pool)
    order = []
    def next_id():
        nonlocal order
        if not order:
            order = ids[:]; random.shuffle(order)
        return order.pop()

    step = 0; micro = 0; running = 0.0; nseen = 0
    opt.zero_grad(set_to_none=True)
    while micro < total_micro:
        eid = next_id()
        ex = ex_by_id[eid]; comp_text = targets[eid]
        # prompts — the harness's OWN builders (train == inference)
        slm_prompt = H._build_qa_answer_prompt_preserving_query(ex, include_docs=True, tokenizer=slm_tok, max_length=a.max_length)
        lm_prompt = H._qa_answer_prompt(ex, include_docs=False)
        slm_pref = prepare_inputs(slm_tok, slm_prompt, max_length=a.max_length)["input_ids"]
        lm_pref = prepare_inputs(lm_tok, lm_prompt, max_length=a.max_length)["input_ids"]
        # ★ KL path: the TEACHER is the SAME 14B with the FULL-context prompt, so it needs no extra model —
        # one forward with the LoRA switched off (see below) gives exactly the eval-ceiling teacher's logits.
        if a.kl_weight > 0 or a.onpolicy_frac > 0:
            t_prompt = H._build_qa_answer_prompt_preserving_query(ex, include_docs=True, tokenizer=lm_tok,
                                                                  max_length=a.max_length)
            t_pref = prepare_inputs(lm_tok, t_prompt, max_length=a.max_length)["input_ids"]
        # ★ TERMINATOR SUPERVISION. The eval loop stops on (a) the newline after the answer line and (b) EOS.
        # Neither was ever in the target before 2026-07-29, so FT could only erode both. Append them (skipping
        # EOS if the completion had to be truncated — that would teach stopping mid-answer).
        comp_ids = lm_tok(comp_text, add_special_tokens=False)["input_ids"]
        truncated = len(comp_ids) > a.max_comp_tokens
        comp_ids = comp_ids[: a.max_comp_tokens]
        if not truncated and a.target_terminator in ("both", "newline"):
            comp_ids += lm_tok("\n", add_special_tokens=False)["input_ids"]
        if not truncated and a.target_terminator in ("both", "eos") and lm_tok.eos_token_id is not None:
            comp_ids.append(int(lm_tok.eos_token_id))
        comp = torch.tensor([comp_ids], dtype=torch.long)
        T = comp.shape[1]
        if T < 2:
            continue
        Ps, Pl = slm_pref.shape[1], lm_pref.shape[1]
        # ★ ON-POLICY (DAgger): replace the teacher's completion with the STUDENT'S OWN rollout, then let the
        # teacher label every position of it. Teacher forcing only ever visits states the TEACHER produces; at
        # inference the fusion follows its own prefix and never saw those states in training.
        if a.onpolicy_frac > 0 and random.random() < a.onpolicy_frac:
            k = random.randint(2, max(2, min(a.onpolicy_max_tokens, T)))
            with torch.no_grad():
                cs, cl = slm_pref.to(dev), lm_pref.to(dev)
                sp, lp, roll = None, None, []
                for step_i in range(k):
                    so = slm(cs if sp is None else cs[:, -1:], past_key_values=sp, use_cache=True)
                    lo = lm(cl if lp is None else cl[:, -1:], past_key_values=lp, use_cache=True)
                    sp, lp = so.past_key_values, lo.past_key_values
                    Vk = min(so.logits.shape[-1], lo.logits.shape[-1])
                    fz = a.lam * so.logits[:, -1, :Vk].float() + (1 - a.lam) * lo.logits[:, -1, :Vk].float()
                    nxt = int(torch.argmax(fz, -1))
                    roll.append(nxt)
                    nt = torch.tensor([[nxt]], device=dev)
                    cs, cl = torch.cat([cs, nt], 1), torch.cat([cl, nt], 1)
                # ONE expert query: the teacher's argmax at every position of the student's prefix
                with lm.disable_adapter():
                    ti = torch.cat([t_pref.to(dev), torch.tensor([roll], device=dev)], 1)
                    tlog = lm(ti, use_cache=False, logits_to_keep=k + 1).logits[:, :k, :]
                lab = torch.argmax(tlog, -1)[0]                      # [k] teacher labels for those states
            comp = torch.tensor([roll], dtype=torch.long)             # student states...
            tgt = lab.reshape(-1)                                     # ...supervised by the expert
            T = k
        else:
            tgt = comp.reshape(-1).to(dev)
        slm_full = torch.cat([slm_pref, comp.cpu()], dim=1).to(dev)
        lm_full = torch.cat([lm_pref, comp.cpu()], dim=1).to(dev)
        tgt = tgt.to(dev)

        if a.train_slm:
            slm_logits = slm(slm_full, use_cache=False).logits[:, Ps - 1: Ps - 1 + T, :]
        else:
            with torch.no_grad():
                slm_logits = slm(slm_full, use_cache=False).logits[:, Ps - 1: Ps - 1 + T, :]
        lm_logits = lm(lm_full, use_cache=False).logits[:, Pl - 1: Pl - 1 + T, :]
        V = min(slm_logits.shape[-1], lm_logits.shape[-1])
        sl = slm_logits[..., :V].float(); ll = lm_logits[..., :V].float()
        if gate is not None:
            feats = build_gate_features(sl[0], ll[0], gate_top_k=a.gate_top_k)   # [T, 2k]
            lam_t = gate(feats).unsqueeze(0)                                     # [1, T, 1] in (0,1)
            fused = lam_t * sl + (1.0 - lam_t) * ll
        else:
            fused = a.lam * sl + (1 - a.lam) * ll
        loss_ce = F.cross_entropy(fused.reshape(-1, V), tgt)
        loss = loss_ce
        if a.kl_weight > 0:
            # ★ SOFT-TARGET DISTILLATION. Hard-token CE uses only the teacher's argmax; KL against the teacher's
            # FULL next-token distribution is the objective that actually corresponds to "reproduce the teacher's
            # output". The teacher = this same LM with the LoRA disabled and the FULL-context prompt, so it costs
            # one extra no-grad forward and zero extra memory. logits_to_keep=T+1 keeps only the positions we
            # score (a 10k-token context would otherwise materialise a ~3 GB logits tensor).
            with torch.no_grad():
                with lm.disable_adapter():
                    t_full = torch.cat([t_pref, comp], dim=1).to(dev)
                    t_out = lm(t_full, use_cache=False, logits_to_keep=T + 1).logits[:, :T, :]
            tl = t_out[..., :V].float()
            tau = a.kl_temperature
            logp_t = F.log_softmax(tl / tau, dim=-1)
            logp_f = F.log_softmax(fused / tau, dim=-1)
            loss_kl = (logp_t.exp() * (logp_t - logp_f)).sum(-1).mean() * (tau ** 2)
            loss = a.kl_weight * loss_kl + (1.0 - a.kl_weight) * loss_ce
        # --loss-norm token: scale this example's mean-loss by T/T_ref so every TARGET TOKEN carries the same
        # weight (T_ref = mean target length over the corpus, so the overall gradient scale is unchanged).
        # --loss-norm example reproduces the old per-example mean (short targets over-weighted per token).
        scale = (T / t_ref) if a.loss_norm == "token" else 1.0
        (loss * scale / a.grad_accum).backward()
        running += float(loss.detach()); nseen += 1; micro += 1

        if micro % a.grad_accum == 0:
            for g in opt.param_groups:
                g["lr"] = lr_at(step, n_optim, a.lr, a.warmup_frac)
            torch.nn.utils.clip_grad_norm_(trainable, a.grad_clip)
            opt.step(); opt.zero_grad(set_to_none=True); step += 1
            if step % a.log_every == 0 or step == 1:
                print(f"[{step}/{n_optim}] loss={running/max(1,nseen):.4f} (kl_w={a.kl_weight}) lr={opt.param_groups[0]['lr']:.2e} "
                      f"(micro={micro}/{total_micro})", flush=True)
                running = 0.0; nseen = 0

    os.makedirs(a.out, exist_ok=True)
    lm.save_pretrained(a.out); lm_tok.save_pretrained(a.out)   # LM adapter at OUT (loaded via --lm-lora OUT)
    slm_out = None
    if a.train_slm:
        slm_out = a.out.rstrip("/") + "_slmada"
        os.makedirs(slm_out, exist_ok=True)
        slm.save_pretrained(slm_out); slm_tok.save_pretrained(slm_out)  # SLM adapter (loaded via --slm-lora OUT_slmada)
        print(f"[Done] SLM adapter -> {slm_out}", flush=True)
    gate_path = None
    if gate is not None:
        gate_path = os.path.join(a.out, "fusion_gate.pt")
        # dual-format so BOTH eval paths load it: mtrag_accum --gate reads the flat keys; run_evidence_sketch
        # --load-weight reads the `config` sub-dict (logit_topk TokenAgnosticGateMLP, input_dim=2*top_k).
        torch.save({"state_dict": gate.state_dict(), "gate_top_k": a.gate_top_k, "gate_hidden": a.gate_hidden,
                    "type": "TokenAgnosticGateMLP",
                    "config": {"gate_feature_type": "logit_topk", "hidden_dim": a.gate_hidden,
                               "gate_top_k": a.gate_top_k, "gate_mlp_layers": 1, "fusion_mode": "weighted_sum"}},
                   gate_path)
        print(f"[Done] learned gate -> {gate_path}", flush=True)
    try:
        import scripts.bench_config as _BC
        _commit, _psha = _BC.code_commit(), _BC._sha(_BC.prompt_text("QA_FULL_CONTEXT_INSTRUCTION_REASON"))
    except Exception:
        _commit, _psha = None, None
    json.dump({"lm_model": a.lm_model, "slm_model": a.slm_model, "lam": a.lam, "doc_number": a.doc_number,
               "max_length": a.max_length, "f1_threshold": a.f1_threshold, "n_examples": len(ids),
               "gold_gate_used": bool(a.f1_threshold > 0), "require_reasoning": bool(a.require_reasoning),
               "target_terminator": a.target_terminator, "loss_norm": a.loss_norm, "code_commit": _commit,
               "kl_weight": a.kl_weight, "kl_temperature": a.kl_temperature,
               "onpolicy_frac": a.onpolicy_frac, "onpolicy_max_tokens": a.onpolicy_max_tokens,
               "mix_corpus": a.mix_corpus, "max_comp_tokens": a.max_comp_tokens,
               "optim_updates": n_optim, "grad_accum": a.grad_accum, "lr": a.lr, "epochs": a.epochs,
               "lora_r": a.lora_r, "lora_alpha": a.lora_alpha, "teacher_log": a.teacher_log, "train_slm": a.train_slm,
               "slm_adapter": slm_out, "learn_gate": a.learn_gate, "gate_path": gate_path,
               "gate_top_k": (a.gate_top_k if gate is not None else None),
               "answer_prompt_variant": os.environ.get("ANSWER_PROMPT_VARIANT"), "prompt_sha_reason_variant": _psha},
              open(os.path.join(a.out, "fusion_distill_meta.json"), "w"), indent=2)
    print(f"[Done] LM adapter -> {a.out}", flush=True)


if __name__ == "__main__":
    main()
